/****************************************************************/
/*    NAME: Konstantinos Roussos                                */
/*    ACCT: cs032082                                            */
/*    FILE: KRUtility.H                                         */
/*    ASGN: Spreadsheet                                         */
/*    DATE: Sat Mar  5 10:33:04 1994                            */
/****************************************************************/


#ifndef KRUTILITY_HEADER
#define KRUTILITY_HEADER

void ClearOut(char* string, int length);



#endif
